### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by tsadarsh** [tsadarsh/zoomferous#1]
Development of UI using popular and easy to use library for **Zoomferous**.

**GUI Library used:  "*To be updated by Assignees*"**

Feature requirement in the GUI:
 - [ ] Dual display in root window. One for raw camera feed and another for masked frame.
 - [ ] Ink color chooser. Button with color pick icon.
 - [ ] Toggle ON/OFF for color in mask.
 - [ ] Reset button for choosing corner points.
 - [ ] Help button directs to website

**Comment by tsadarsh** [comment]
There is no `gui.py` file in **gui** branch.

**Comment by soumilbaldota** [comment]
it is chck.py

**Comment by soumilbaldota** [comment]
will update

**Comment by tsadarsh** [comment]
We should look into Kivy.
> It supports multitouch events in addition to regular keyboard and mouse inputs. Kivy even supports GPU acceleration of its graphics, since they’re built using OpenGL ES2. The project uses the MIT license, so you can use this library for free and commercial software.
