### ISSUE TITLE
Webiste for Zoomferous

### ISSUE THREAD

**Issue by tsadarsh** [tsadarsh/zoomferous#2]
We need a static website for this product.

Main pages required:
 - [x] Home Page
 - [x] Downloads Page
 - [x] Help Page
 - [x] About

**Comment by tsadarsh** [comment]
Download link: https://github.com/tsadarsh/zoomferous/releases/download/v1.0/Zoomferous.zip
Github Repo link: https://github.com/tsadarsh/zoomferous

**Comment by tsadarsh** [comment]
I like the new website :+1: 
We still need to make it **responsive**.

**Comment by Sanjeeban2411** [comment]
yes, will be working on it
